### PR TITLE
FIX: parent widget pops with toast

### LINKED ISSUE #72: Parent widget pops when toast dismisses
## Issue
When `dismissable` is set to `true`, sometimes the parent widget which called `MotionToast` pops with the toast itself.

This generally happens when user taps on screen at the same time the `MotionToast` is dismissing.

## Bug Video
https://user-images.githubusercontent.com/74326345/178607165-99c710e2-07c7-48c5-b6b8-32320db2f829.mp4

### LINKED ISSUE #78: Parent element poped when while motiontaost is visible and keyboard is opened.

### PR DESCRIPTION
**Pull request by OutdatedGuy**
## Changes
- Only pop till the current route (i.e. toast widget) is at the top
- Check if toast widget is mounted before trying to pop

# Note
This change seems to pass the integration test. Also I have tried it on many other examples and it seems to work fine.

However, I have **NO** idea how it works. It might also cause crashes.

Resolves #72, might resolve #78

### CODE REVIEW

File: lib/motion_toast.dart [hunk 1]
```diff
@@ -436,9 +436,11 @@ class _MotionToastState extends State<MotionToast>
     toastTimer = Timer(
       widget.toastDuration,
       () {
-        slideController.dispose();
-        Navigator.of(context).pop();
-        toastTimer.cancel();
+        if (mounted) {
```
Comment (koukibadr) [inline lib/motion_toast.dart:439]:
```dart
 if (mounted) {
        Navigator.of(context).popUntil(
            (route) => route.isCurrent,
         );
   }
```

Duplicated code as in the line 521, try refactor it in a seperate private callback (`_popCurrentToast`)

Comment (OutdatedGuy) [reply lib/motion_toast.dart]: Done
